### PR TITLE
Replace closest function with polyfill

### PR DESCRIPTION
**Pull request by sphilee**
Is this okay? I refer to the link below.

https://developer.mozilla.org/ko/docs/Web/API/Element/closest

### CODE REVIEW

**Comment by zenorocha** [comment]
Hey @sphilee, what behavior are you trying to fix?

**Comment by sphilee** [comment]
@zenorocha This does not fix the bug. however Would not it be faster to use the Web API?

**Comment by fregante** [comment]
`delegate` is not a polyfill, therefore it should not polyfill any API, especially if unrelated to its name.

The only change I'd bring to this area would be to extract `closest` to its own module (or an existing one)

**Comment by zenorocha** [comment]
Thanks for the input @bfred-it! I'm fine with using the `closest` package again if they're maintained.

**Pull request closed without merging**
